language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: aD2qzD5VHEp5ZKZGtVi7ujWUVwzjiCnV08CvO/L3OJJswncpRTYXJvMLY513PSKAOV0EDEFgAM2kVppblje17yu7pdFznSSISYqbZH6ZUS0vgVZ68j9ma24imPFXAL1RU1l6RTjAs937XHtLic6O9IOwBv69Gh/6KpyU/AhXIuU=
  on:
    tags: true
    all_branches: true
