language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: XCe80k6naVN1DgNBrhTJnY0zuH8K/6XjljwRRPo8QhTYuMeLojA8DTOUxXGvBtsDuVfHIL+zg5H1pyrsB1wVcEDxVccjv9b5J3NIJCAKKPbDLoWoT7UWQgD+UXkdtf5vJN+xKPojVjzQtqN9VdfNZqKv1JxJBbyiEBPyJDJb3Ow=
  on:
    tags: true
    all_branches: true
